### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#1]
So I'll help write tests. Anyone have an opinion on what they'd like to use? I thought the simplest thing might be Mocha/BDD/JSDOM.

Thoughts. Votes.

**Comment by dperrymorrow** [comment]
I would be willing to write some tests as well. 
If it were up to me I would choose Karma with Jasmine. Purely from the standpoint of thats what I have the most experience with.

Karma will let you test in many different browsers easily which I'm expecting to be important on a project like this.

http://karma-runner.github.io/0.13/index.html

**Comment by zdfs** [comment]
I don't mind Karma, I just hate configuring it. You want to pick up that part?

**Comment by dperrymorrow** [comment]
sure thing, karma works great with mocha too, wanna use that instead of Jasmine?

**Comment by zdfs** [comment]
Yeah. I like Mocha more than Jasmine. But either way works. I've used them all at some point. The syntax will basically be the same.

**Comment by dperrymorrow** [comment]
there ya go...

**Comment by lipis** [comment]
Would be nice to setup TravisCI as well..

**Comment by LeaVerou** [comment]
You guys rock, thanks!
And yes, I will set up TravisCl once we have some tests :)

**Comment by dperrymorrow** [comment]
:+1: for sure, would be nice to see that tests are passing on pull requests.

**Comment by LeaVerou** [comment]
Hmm, anyone has any idea why Travis doesn't seem to be working? I activated this repo on travis-ci.org, I added a .travis.yml file, nothing… What did I forget?

**Comment by zdfs** [comment]
@LeaVerou I'm wondering if it's because there's nothing in the master branch. Could be that we need to tell Travis that we're not using master somehow?

**Comment by zdfs** [comment]
Try something like?

```
# whitelist
branches:
  only:
    - gh-pages
```

**Comment by zdfs** [comment]
Ah. Here we go. Seems like this is the official answer. http://stackoverflow.com/questions/12878568/travis-ci-triggers-build-only-for-master-branch-in-github-repo

**Comment by zdfs** [comment]
Ok. We have builds and a testing framework. Closing this out. We should probably make individual issues for needed tests.
