### ISSUE TITLE
$.remove fails on IE11

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#105]
Tested on full version (minified and developement), the test code is simple, does not load anything else:
```html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>TEST</title>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <script src="modules/!core/js/3rd/bliss/bliss.min.js"></script>
</head>
<body class="pt">
<script>
    alert([!!$, !!$.remove, !!$.include]);
</script>
</body>
</html>
```

And it alerts: `true,false,true`

I'm getting errors about $.remove each time I try to use `include` (Promises polyfill is loaded before).

**Comment by dzek69** [comment]
Okay, looks like Element `remove` polyfill needs to be applied before loading Bliss. The `$.include` example with es5-sham misguided me, I thought "manually" loading Promises polyfill, then loading other polyfills via Bliss would be enough to make everything work.

I don't know if something should be done about that, probably not.

**Comment by LeaVerou** [comment]
`$.remove` is not a Bliss method, it's just a native method that (just like all native HTMLElement methods) is added to `$` as well (to handle arrays etc). Therefore, obviously in browsers that don't support `element.remove()` it will not be available without a polyfill. :)

**Comment by LeaVerou** [comment]
That said, the polyfill is as easy as:
```js
if (!('remove' in Element.prototype)) {
  Element.prototype.remove = function() {
    this.parentNode && this.parentNode.removeChild(this);
  }
}
```
