### ISSUE TITLE
Event delegation does not match ancestors 

### ISSUE THREAD

**Issue by TxHawks** [LeaVerou/bliss#106]
element.matches(selector) does not match ancestors, which can often be an issue.

For instance, a very common pattern is for a button to have an icon inside it, next to a text node: ![image](https://cloud.githubusercontent.com/assets/5658514/11786217/18cbe0dc-a28e-11e5-9609-4f52ffc63f44.png)

Reasonably, one would do `$.delegate(someWrapper, click, myButton, callback)` to delegate clicks to the button.

However, user will often click on the icon, in which case `event.target` will be, well, the icon, and the event will not be fired.

The easiest way to fix this is to switch `evt.target.matches(selector)` with `evt.target.closest(selector)` in [line 496](https://github.com/LeaVerou/bliss/blob/gh-pages/bliss.shy.js#l496). The problem is that [support for element.closest is pretty narrow](http://caniuse.com/#feat=element-closest). However, there is a [really tiny polyfill](https://github.com/jonathantneal/closest/blob/master/closest.js).

I know the `Bliss` philosophy is opposed to including polyfills, but since this is so tiny and useful for delegation, it might be worth it to make an exception in this case.

If this makes sense, or if someone can think of a better solution, I'm happy to send a pull request.

**Comment by guoguo12** [comment]
Well, that makes sense. But couldn't you use something like

```js
$.delegate(someWrapper, "click", "#myButton, #myButton *", callback)
```

to achieve the desired behavior? I think adding the functionality you described could be confusing (and hard to fix) in cases where you _don't_ want children of the selector to trigger the event.

**Comment by zdfs** [comment]
I may be wrong, but this also seems like something pointer-events solves.

**Comment by guoguo12** [comment]
@zdfs: Interesting, I didn't know about pointer-events. How would you use it to solve the problem above?

**Comment by zdfs** [comment]
I believe that you could just set `pointer-events: none` on the icon and then any events on the icon would bubble up.

**Comment by guoguo12** [comment]
Oh okay, that's neat. Any thoughts, @TxHawks? Thanks for helping out, by the way! :smiley:

**Comment by praveenpuglia** [comment]
pointer-events doesn't stop the keyboard though. 
https://jsfiddle.net/pgs23r8o/

**Comment by LeaVerou** [comment]
Shouldn't the icon be in CSS (background or generated content) instead of an HTML element that receives events?
Also, if it's properly nested, click events bubble anyway, you don't need delegation (unless you need it to e.g. handle all sign in buttons on a page at once).
Anyway, support for `closest` is not a problem. It fulfills both criteria: It's both polyfill-able and supported in all modern browsers. I think it's even used somewhere else in Bliss already.
Apart from browser support, does anyone have any objections to this suggestion? Are there any use cases where it would be a problem to match children too? If not, I'd welcome a PR to change `matches` to `closest`.

**Comment by TxHawks** [comment]
@guoguo12 - `$.delegate(someWrapper, "click", "#myButton, #myButton *", callback)` works, but is more verbose and requires more planing.

@LeaVerou - You may argue the merit of this, but it's definitely not uncommon to not have the icon in css, for example when using svg icon systems with `<use>`. 
Re support level for `closest`, it isn't supported in anything Microsoft, including Edge.

Since it's not going to take more than a few minutes, I'll send a PR in a bit, so that it's ready if this change is ruled  desirable.

**Comment by guoguo12** [comment]
Closing this out (#109 merged).
