### ISSUE TITLE
Polyfill bundle

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/bliss#108]
I know we recommend polyfills to people, but sometimes we're using bits that would be extremely small polyfills and people would still have to hunt them down and include them separately (e.g. see discussion in #106 about `element.closest()`). I've also heard from a non-web dev colleague that the overhead of hunting down polyfills to use Vanilla JS is just way too much for someone not too immersed in this stuff.

What would you think about providing a bundle of polyfills that people could download along with Bliss? We could even have multiple bundles, for multiple levels of desired browser support!
They don't have to be homemade, they can be fetched from multiple sources (does gulp have a plugin that does this with URLs instead of local paths?) with appropriate credit.

Thoughts?

**Comment by zdfs** [comment]
I think that might be a good idea. Just a cursory search for `gulp remote src` turns up some interesting results.

**Comment by TxHawks** [comment]
+1

**Comment by praveenpuglia** [comment]
+1

**Comment by wcastand** [comment]
Do you want something like that ? 
[link](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills)

**Comment by dperrymorrow** [comment]
would this be done manually, or using NPM dependancies and having a separate gulp task to build it?

I think this is a great idea, and could be used in conjunction with hooking up travis with the whole suite of browsers we would like to support.

**Comment by TxHawks** [comment]
Maybe we can suggest a polyfill service like this: [https://cdn.polyfill.io/v1/docs/](https://cdn.polyfill.io/v1/docs/)?

**Comment by dperrymorrow** [comment]
oh, thats pretty nice...

**Comment by praveenpuglia** [comment]
we can probably upgrade the polyfill section to contain some of these links and update the browser support table in readme to reflect the real support of base bliss.

**Comment by LeaVerou** [comment]
That’s awesome, nice find @TxHawks!! Yes, we should totally include isntructions about how to use this service instead of a polyfill bundle or list of polyfills!

**Comment by jbmonroe** [comment]
Not a polyfill, but a ponyfill (see Ponyfoo.com):

    var from = Array.from || Array.prototype.slice;

Then

    // In the future, we should use Array.from() instead of Array.prototype.slice.call() -- solved!
    return from.call(typeof expr == "string"? (context || document).querySelectorAll(expr) : expr || []);

**Comment by lukeed** [comment]
Glad this convo is in the works.

The polyfill service **does** *sound* great, especially since you can specify `?features=[]`, but that'll leave it up the user to define this array, when it's Bliss that (currently) needs x,y,z polyfills.

Supplying our own poly/pony fills allows us to target specific minimum support, and we know what we'll need & when to drop them.

Also, at the end of the day, there'll be less of a footprint because the polyfills will be gzipped & there'll be fewer requests made.

**Comment by LeaVerou** [comment]
@jbmonroe this is against Bliss’ philosophy. No polyfills in Bliss core code. Polyfills should be separate and Bliss should just use that native APIs. This is the philosophy of the project and it's not going to change.

That said, now that we recommend polyfill.io, we can use Array.from() just fine. I love this service!!

**Comment by lukeed** [comment]
@LeaVerou hmm.. i guess i have trouble thinking of Bliss as just a native wrapper & not meant as a total code base/foundation and/or jquery replacement for the masses

**Comment by LeaVerou** [comment]
If you want to use Bliss that way, just include polyfill.io as well and you're all set. :)
There is so much good polyfill code around, it's pointless to be inventing our own polyfills and burying them in Bliss code. It increases maintenance work & bloat, and decreases code quality & readability.
