### ISSUE TITLE
Prefer natives

### ISSUE THREAD

**Issue by benjamingr** [LeaVerou/bliss#11]
Hey, some of the methods in bliss duplicate stuff native JavaScript does - I think it would be nice if bliss polyfilled these methods instead of duplicating them. For example: `$.extend` and `Object.assign`.

**Comment by LeaVerou** [comment]
`Object.assign()` is not the same thing as `$.extend()`. This is pointed out in [the docs](http://blissfuljs.com/docs.html#fn-extend).
