### ISSUE TITLE
$.add method bug

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#110]
According to documentation I can use:
`$.add(name, callback [, on])`
or
`$.add(callbacks [, on])`

But after looking at the code - you will notice that first way won't work as expected. Callback will be used as `on` object (so `on` is totally ignored), `noOverwrite` will always evaluate to true if anything was passed. New method will be added, thanks to recreation of `methods` object and it will work on `element` and `array`, but it will fail on `$` if used this way.

**Comment by StrongRef** [comment]
I will have a go at this one.

**Comment by dzek69** [comment]
how about noOverwrite? it will always be true if I run this method as:
`$.add('name', callback, {$:false}`

Also documentation doesn't say a word about `noOverwrite`, plus

**Comment by StrongRef** [comment]
You can set noOverwrite if you use the alternative signature `$.add({ name: callback }, {$:false}, false)`

If my solution isn't elegant enough, please improve it...

**Comment by dzek69** [comment]
i'd have to learn myself github usage first ;)
i'll consider this

**Comment by LeaVerou** [comment]
This bug will likely be solved automatically once #69 is addressed (which is yet another reason to do this asap)

**Comment by StrongRef** [comment]
Ok, I'll close my PR!

**Comment by dperrymorrow** [comment]
@StrongRef I'm working on #69 now, if anybody wants to work on tests for ```$.add``` that would be super!

**Comment by StrongRef** [comment]
@dperrymorrow I'll have a go at it again tomorrow!
Trying to clean up `$.fetch` tests right now.

**Comment by dperrymorrow** [comment]
awesome, thanks so much...

**Comment by StrongRef** [comment]
@dperrymorrow Let me know if the tests aren't thorough enough!

**Comment by StrongRef** [comment]
This one is resolved, right?

**Comment by LeaVerou** [comment]
This should be fixed after merging #148 . Feel free to reopen if not!
