### ISSUE TITLE
$.fetch method won't set `search` part of URL when GET will be specified as method but not in uppercase

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#111]
```javascript
o.method = o.method || 'GET';
// ...
if (o.method === "GET" && o.data) {
	url.search += o.data;
}
// and few more times it's compared like that
```

well, specification says method is case sensitive, but some servers will accept method regardless of case of letters, some will reject requests

all methods used to be uppercase anyway, so it's probably good idea to always uppercase it, just to make coding easier

**Comment by praveenpuglia** [comment]
I think this makes sense but Lea should be confirming this.

**Comment by praveenpuglia** [comment]
The PR can be merged if this makes sense. @LeaVerou should make the call.
