### ISSUE TITLE
Tests for $.around

### ISSUE THREAD

**Issue by praveenpuglia** [LeaVerou/bliss#112]

**Comment by praveenpuglia** [comment]
I can write tests for this. @zdfs - can you assign this to me so two people aren't working on this one?

**Comment by zdfs** [comment]
I thought there was a spec in there already?

**Comment by praveenpuglia** [comment]
Did't see it in issues/PRs. Is it there?

**Comment by praveenpuglia** [comment]
Oh it does! nevermind! closing this.
