### ISSUE TITLE
Wrap querySelector and querySelectorAll in a try/catch block

### ISSUE THREAD

**Issue by softwarespot** [LeaVerou/bliss#116]
I didn't want to create a PR if this was out of scope for the library.

I am simply wondering would it be better to wrap querySelector and querySelectorAll in a try/catch block and return an empty array just like sizzle/jQuery does?

**Comment by zdfs** [comment]
I don't think that we want to make everything a collection. Bliss' purpose is to make using native JavaScript easier, and native JavaScript doesn't return everything as a collection. Make sense?

**Comment by LeaVerou** [comment]
Yup. If you want everything to be a collection just use $$ exclusively and you're all set :)

**Comment by softwarespot** [comment]
@zdfs it makes sense. I just didn't know if you were trying to be a little like jQuery. But thanks for answering =)

**Comment by LeaVerou** [comment]
Not really. If something in jQ is a good idea and needed commonly enough we might consider it, but similarity for the sake of similarity is not a design goal. :)
