### ISSUE TITLE
media query breakpoint is too high for nav

### ISSUE THREAD

**Issue by dperrymorrow** [LeaVerou/bliss#119]
looks like the breakpoint for when the nav goes to the top (block) needs to be set larger.

![bliss js documentation 2015-12-14 19-30-34](https://cloud.githubusercontent.com/assets/64978/11801292/44e8b3ce-a299-11e5-99e7-61a16269a821.png)

**Comment by zdfs** [comment]
I can take a look at this.

**Comment by dperrymorrow** [comment]
sorry to be a pain, but now the nav is going verical at a different break point that at which it goes to two columns.

![bliss js documentation 2015-12-14 22-22-22](https://cloud.githubusercontent.com/assets/64978/11803608/43121500-a2b1-11e5-9809-713122446e18.png)

**Comment by LeaVerou** [comment]
Gah. This width and height MQ combination ended up being such a PITA :(
Thanks for looking into it @zdfs!

**Comment by zdfs** [comment]
I submitted some changes to match the breakpoints up (sorry I missed that). Do we need anything else for now?

**Comment by LeaVerou** [comment]
Guess not :) Thanks @zdfs!
