### ISSUE TITLE
element.remove() $.remove() needs polyfill

### ISSUE THREAD

**Issue by lukeed** [LeaVerou/bliss#124]
Not supported at all in IE. 
Otherwise, Safari 7, Opera 10, FF 23 and Chrome 23.

**Comment by dzek69** [comment]
This library is not about polyfills and making everything cross-browser.
I've already mentioned $.remove problem in #105 but I just got misguided by example of loading ES5-sham via Bliss (which has polyfill for `remove` method) - cause it will throw an error just after loading it this way with browsers that doesn't support `remove`, which makes this example weird

@LeaVerou what I think it'd be worthy to add is some `reattach DOM methods to Bliss` method built-in, so I can first load Bliss, then load polyfills and they will work with Bliss.

**Comment by lukeed** [comment]
I mention it because the repo's [readme](https://github.com/LeaVerou/bliss/blob/gh-pages/README.md) states claims specific browser version support.

And since `$.remove()` *is* mentioned within the documentation, there exists a disparity.

Either a simple polyfill (as @LeaVerou mentioned) finds its way into the library so that the browser claims hold true, or a **really noticeable** notice should be included around its documentation.

**Comment by dzek69** [comment]
Well, technically it does work, just attaches to Bliss the methods that available to browser. The problem is that Bliss is internally using methods that may not exist on specific browsers while claiming it will work  on those, so you're right, thanks for poiting that out.

**Comment by LeaVerou** [comment]
The browser support table implies use of polyfills. Will be made much more clear with #108 as well.
