### ISSUE TITLE
$.fetch data stringification is too simple

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#128]
```javascript
$.fetch('tests/ui.php', {data:{test:{'a':1,'n':2}}})
```
results in server getting weird string:
```php
 [GET] => Array
        (
            [test] => [object Object]
        )
```
and
```javascript
$.fetch('tests/ui.php', {data:{test:[1,2]}})
```
causes comma separated values:
```php
[GET] => Array
        (
            [test] => 1,2
        )
```

jQuery results (from `$.get`, same params syntax) are as expected:
```php
[GET] => Array
        (
            [data] => Array
                (
                    [test] => Array
                        (
                            [a] => 1
                            [b] => 2
                        )

                )

        )
```
and:
```php
[GET] => Array
        (
            [data] => Array
                (
                    [test] => Array
                        (
                            [0] => 1
                            [1] => 2
                        )

                )

        )
```

**Comment by dperrymorrow** [comment]
would you be willing to start writing some tests for ```$.fetch```?
i have an example of a testing strategy here #130

**Comment by dzek69** [comment]
sad to say, but i've never do any tests and xhr tests sounds like more trouble than to test a simple function :(

**Comment by LeaVerou** [comment]
Yeah, currently it does very simple serialization, it's not intended for nested objects. Is this useful? If so, I can look into adding it.
While I'm at it, perhaps we need to remove the serialization code from `$.fetch()` and have a separate helper to serialize objects in custom ways. Need to make sure this won't add more bloat than it's worth though.
Thoughts, everyone?

**Comment by dzek69** [comment]
For me it's extremely useful. Imagine something simple as:
```html
Fav colors:
<select multiple name=colors>
<option>green</option>
<option>red</option>
<option>blue</option>
</select>
```

Then I select two items, for server side code it would be totally weird not to receive an array here, but comma separated values. What if I want to have comma separated value in my select?

If simple example doesn't convince you:

Imagine a web application where I'd like to create an invoice. Well, I have one, and while I'm rewritting some parts of UI - I'm implementing Bliss.

```html
[Some "single" stuff, like receiver name, VAT ID, date of issue etc]
Stuff I sold:
<button>[+] add item</button>
<div class=item>
<button>[-] remove</button>
<input name="item[][name]" value="something i sold" />
<input name="item[][price]" value="1337" />
<input name="item[][amount]" value="5" />
</div>
<div class=item>
<button>[-] remove</button>
<input name="item[][name]" value="something else" />
<input name="item[][price]" value="10" />
<input name="item[][amount]" value="1.5" />
</div>
```

I've already done the parsing of names like `item[][amount]` and I don't think it should be Bliss problem to prepare such data (`document.forms` should do this automatically too btw, but in my webapp for some reason I'm not using this).

But sending nested objects data is a must-have for me. Without this `fetch` seems to be useless on webapps.

(And yes, I can just pack it up into a single JSON and unpack it on the server, but why we are having multiple form items if not for sending multiple values separately? Also if I'd like to use some external API, where I cannot modify server-side code - I'd not be able to use Bliss do communicate with API)

**Comment by StrongRef** [comment]
It would be nice to move the serialization part away from `fetch`.
Since different projects have different requirements, perhaps built-in support for a simple, straightforward serialization but with the possibility to add your own implementation.

**Comment by LeaVerou** [comment]
Now that we have hooks (see c8ede04061cf16a13a10cd7d5d149fd49ad46602 ), I’m thinking about removing the object functionality altogether and just adding a hook there so that people can handle `o.data` in any custom way they want.
This way, we could have a plugin that do what the OP wants, and keep Bliss lean :) Thoughts?

**Comment by praveenpuglia** [comment]
Sounds great to me! We don't wanna be gigantic-we-do-it-all library. :)

**Comment by dperrymorrow** [comment]
polyfills and user customization for the win, this ain't JQuery

**Comment by LeaVerou** [comment]
Awesome. I’ve done that in 1f2233a1f15de3d4bbfe121bc3b678564597c6c7. @dzek69 now you can publish a plugin that does this very thing! (soon we'll have an official plugin catalog too, see #125
