### ISSUE TITLE
Calling $.create with no arguments creates element

### ISSUE THREAD

**Issue by kimroen** [LeaVerou/bliss#13]
When running this code:

```js
var myElement = $.create();
```

`myElement` is an `Element` with `tagName` `UNDEFINED` (like `<undefined></undefined>`).

It should probably either throw a `TypeError` complaining about the number of arguments (like `document.createElement`), or create a `div`, like passing in an empty object does.

**Comment by LeaVerou** [comment]
Yeah, it should just create a div. Good catch! Just pushed a quick fix, hope it works!
