### ISSUE TITLE
tests for $.fetch

### ISSUE THREAD

**Issue by dperrymorrow** [LeaVerou/bliss#130]
We need tests for ```$.fetch```, have had a few of issues reported around this method #111 #127 #128 #91 , and its difficult to begin making changes without tests in place.

a good testing strategy would be to use ```sinon.server``` 
https://gist.github.com/cjohansen/739589

**Comment by StrongRef** [comment]
I created a simple template for testing `$.fetch`.

For now it's just echoing the request data back to the client. However, we have to discuss whether #128 is still a valid bug though. Should we improve the way data is stringified?

**Comment by dperrymorrow** [comment]
great thanks for helping. much appreciated.

**Comment by StrongRef** [comment]
Ugh, I will create a new PR with tests for fetch soon.
I somehow managed to do a bad merge i think...

**Comment by LeaVerou** [comment]
Argh. On it, thanks for spotting!

**Comment by dperrymorrow** [comment]
$.fetch tests have been merged in no? closing this.
