### ISSUE TITLE
Smallest clouds in docs header have outlines on FF

### ISSUE THREAD

**Issue by guoguo12** [LeaVerou/bliss#131]
Anyone else seeing this?

![temp](https://cloud.githubusercontent.com/assets/1940729/11819427/963e8354-a314-11e5-89e0-fdf39bb817c1.png)

I'm using Firefox Developer Edition 44.0a2 on Windows 8.1.

**Comment by zdfs** [comment]
I don't see it. Probably a bug in the Developer version?

**Comment by guoguo12** [comment]
Weird, okay.

**Comment by LeaVerou** [comment]
Cannot reproduce either. I do remember this being an issue in the past though, because I was depending on premultiplied RGBA interpolation which Firefox doesn't have. Could it be that your cache is very aggressive or something and still has the old version?

**Comment by guoguo12** [comment]
AFAIK, it's not caching. Must be something with Firefox Developer.

**Comment by LeaVerou** [comment]
Looks like you were right, that one was still using `transparent`. Does it work now?

**Comment by guoguo12** [comment]
Yep, that fixed it. Thanks for looking into it!
