### ISSUE TITLE
Builds are failing when trying to install Google Chrome.

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#133]
Seems to be a recent development:

![screen shot 2015-12-15 at 11 53 47 am](https://cloud.githubusercontent.com/assets/619628/11822262/9b102776-a322-11e5-89a4-b85366d4690b.png)

**Comment by zdfs** [comment]
Maybe we need to enable more repos? http://askubuntu.com/questions/378558/unable-to-locate-package-while-trying-to-install-packages-by-apt

**Comment by LeaVerou** [comment]
Is this why Travis started failing after I pushed a change to …the website?

**Comment by zdfs** [comment]
Looks like we needed `sudo apt-get update` in our `.travis.yml`. Builds seem to be succeeding now. Closing out.
