### ISSUE TITLE
Hook system, to make Bliss way more extensible

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/bliss#137]
I’m thinking of adding a lightweight hooks system just like the one in [Prism](https://github.com/PrismJS/prism/blob/gh-pages/prism.js), and which has been very successful so far.

**How it works:** Hooks are tied to identifiers and the system has two methods: `$.hooks.run(id, env)` and `$.hooks.add(id, callback)`. The former executes any code tied to a specific hook, passing the environment to the callback via the `env` object. The latter adds code to be run every time a certain hook is executed.

A hook system allows people to essentially change how Bliss works, which makes it much more flexible than the few extension points we currently have.

Thoughts?

**Comment by zdfs** [comment]
:+1:

**Comment by LeaVerou** [comment]
Added via c8ede04061cf16a13a10cd7d5d149fd49ad46602 !
