### ISSUE TITLE
Hooks for everyone!

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/bliss#147]
I just had an idea I’m very happy about.
Instead of having one hooks object just for ourselves, having a hooks **class** that our users can instantiate, to make their own libraries extensible too! Then `$.hooks` will just be one instance of that object!

```js
$.hooks = new $.Hooks();
```

It shouldn't add much to the codebase, and AFAIK it's functionality that no other library has!
/me is excited

**Comment by dperrymorrow** [comment]
yay, sounds pretty interesting.

**Comment by LeaVerou** [comment]
Done! Still needs docs though.
