### ISSUE TITLE
show / hide functionality

### ISSUE THREAD

**Issue by jonathantneal** [LeaVerou/bliss#155]
Would it be helpful to have `.show()` / `.hide()` mapped to `removeAttribute('hidden')` and `setAttribute('hidden', '')`?

**Comment by zdfs** [comment]
I think both `$.style()` and `$.transition()` solves this problem, as well as just adding/removing classes you might have in your CSS. But that's just my personal opinion.

**Comment by praveenpuglia** [comment]
I think the primary idea of bliss is that it makes it relatively easier to work with vanilla JS by creating wrappers for important things. Things that do a lot more than what `.show()`/`.hide()` would do. Also, creating them would encourage other developers to ask for more micro helpers which I think goes out of scope of this library.

**Comment by LeaVerou** [comment]
Agree with the above, but just to mention that if you really want the convenience of show/hide methods, you can trivially implement them yourself:

```js
$.add({
  show: function() { this.removeAttribute("hidden"); },
  hide: function() { this.setAttribute("hidden", ""); }
});
```
