### ISSUE TITLE
Add a wiki

### ISSUE THREAD

**Issue by JacquesMarais** [LeaVerou/bliss#157]
What about a wiki to explain what Bliss is all about?

**Comment by renoirb** [comment]
Did you see [blissfuljs.com](http://blissfuljs.com/)?  Maybe we should put this URL as the project site on the repository.

**Comment by LeaVerou** [comment]
>  Maybe we should put this URL as the project site on the repository.

Yup.

**Comment by JacquesMarais** [comment]
Oh thank you.
