### ISSUE TITLE
More regular releases

### ISSUE THREAD

**Issue by TxHawks** [LeaVerou/bliss#160]
I think there is a need for a better release cycle. NPM and Bower are very common ways in which people consume front end modules, but someone installing Bliss with one of these tools would now get code that is 126 commits behind the current code base.

I'm not saying that every merged commit should trigger a release, but several of those 126 are bug fixes and some (like hooks), are pretty major features.

I realize maintenance is a lot of work and that it is hard to find time, but perhaps we can find a way to automate a lot of this? Bug fixes, I think, should definitely be released asap.

**Comment by LeaVerou** [comment]
Ouch. I will try to make a release today. Thanks for noticing!

**Comment by LeaVerou** [comment]
Done!
In retrospect, it should probably have been 1.1.0 instead of 1.0.1 but oh well.

**Comment by TxHawks** [comment]
Thanks!

Maybe a milestones-based workflow should be established?

That way, it's easy to know when all issues associated with a certain
release are resolved, and when it is safe to release

**Comment by LeaVerou** [comment]
That works well when there are tons of things to do and you need to prioritize. Here there aren't really that many open issues.

**Comment by TxHawks** [comment]
True, but it also just helps with knowing when is a good time to release,
and if it should be a major/minor/patch release.

It's also a good way to not merge breaking changes that you do want to
include at some point right away, But have them conveniently organized as
to not forget about them.

It also gives contributors a sense of when will their code can be expected
to merge, and can make NPM releases automatic and hassle free

If you're worried about the overhead, I'm happy to take managing it on
myself (i.e. the assignment of issues to milestones, you'll still do the
merging yourself, of course).

**Comment by LeaVerou** [comment]
There is currently 1 open pull request and 8 open issues, most of which are enhancements that are often not even about Bliss' code (e.g. Plugin catalog). I really don't think this kind of issue load warrants a milestone-based workflow. There simply aren't enough issues. A workflow like that would work great on bigger projects like Prism, with dozens of issues and open PRs. This currently doesn't have the volume of contribution to benefit from this.
However, thanks for offering to help and I will certainly keep it in mind for the future, when Bliss has more open issues & PRs!
