### ISSUE TITLE
Should `fire` return the results of `dispatchEvent`?

### ISSUE THREAD

**Issue by TxHawks** [LeaVerou/bliss#162]
A [change](https://github.com/LeaVerou/awesomplete/pull/16827) was recently introduced to the `$.fire` helper in [awesomeplete ](https://github.com/LeaVerou/awesomplete/), that returns the value of `this.dispatchEvent()`.

This is pretty useful, and I think it should also be introduced into Bliss's method.

**Comment by LeaVerou** [comment]
What does dispatchEvent return? I thought it returns the element.

**Comment by TxHawks** [comment]
From [MDN](
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent):

> The return value is false if at least one of the event handlers which
handled this event called `Event.perventDefault()`. Otherwise it
returns true.

**Comment by LeaVerou** [comment]
Oh yes, this sounds useful! How did I not know about this? Yes, we should totally add this to Bliss! PR?

**Comment by TxHawks** [comment]
Will do
