### ISSUE TITLE
Polyfill only the things we need

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/bliss#164]
Hi all,

[I talked to the polyfill.io guys](https://github.com/Financial-Times/polyfill-service/issues/594) to add a `blissfuljs` alias to their service, so we can tell people to request polyfill.io with `?features=blissfuljs` instead of the `features=all` we currently recommend, which is super wasteful. Can anyone help me compile a list of features we need here?

**Comment by LeaVerou** [comment]
I’ll start:
```js
Array.from
es5
Promise
Element.prototype.remove
URL
XMLHttpRequest
document.querySelector
```

Did I forget anything?

**Comment by softwarespot** [comment]
Event? >> https://cdn.polyfill.io/v2/docs/features/#Event

**Comment by LeaVerou** [comment]
We don't use that. Maybe we should, but we currently don’t :)

**Comment by LeaVerou** [comment]
[PR sent](https://github.com/Financial-Times/polyfill-service/pull/596)

**Comment by dperrymorrow** [comment]
super cool...
a few that come to mind. Some of these only need polyfilled if we are going to support IE8. 

``` Array.prototype.forEach() ```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
``` Function.prototype.bind() ```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
``` Array.prototype.reduce() ```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
``` Array.prototype.map() ```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by LeaVerou** [comment]
Can you guys please check my PR (which is now merged) before suggesting things?
I believe I have added all 4 of those.

**Comment by LeaVerou** [comment]
Done. http://blissfuljs.com/#browser-support
