### ISSUE TITLE
Issue with Machina.js

### ISSUE THREAD

**Issue by gabrielstuff** [LeaVerou/bliss#168]
Hey, we are trying to move on Bliss but we face some issue.
Here is an example bin : 
http://requirebin.com/?gist=5949db07e001e3b68fec

The example runs perfectly without bliss. As soon as bliss is require it all falls apart and throw undefined. 
As for now I did not investigate much but I guess this approach leads to the issue : 

> Adds $() and $$() global methods and a _ property on elements and arrays, for convenience. Also wraps addEventListener and removeEventListener to track events. Perfect for when you control the environment.

Thanks !

**Comment by gabrielstuff** [comment]
Hmmm, missing a semi :) closing this for now.

**Comment by LeaVerou** [comment]
Ok! Let us know if you run into any other issues :)
