### ISSUE TITLE
$.fetch() with timeout option may never resolve/reject

### ISSUE THREAD

**Issue by nevf** [LeaVerou/bliss#170]
If I specify options: ```{ timeout: 1000 }``` and the request takes longer than this ```fetch()``` never resolves or rejects. 

I only started using bliss today so may have this wrong but adding the following resolves this issue.

````
env.xhr.ontimeout = function() {
    document.body.removeAttribute('data-loading');
	reject(Error("Network Timeout"));
};
````

ref: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Example_using_a_timeout

I'd also suggest moving ```'data-loading'``` out to a ```const``` to save repetition.

I'm looking forward to using Bliss in my Web app Clibu http://myclibu.com and have been on a mission for a while to lose jQuery.

**Comment by LeaVerou** [comment]
No sure if I'm forgetting something, but there doesn't seem to be a timeout option, hence why it doesn't work :P 
I wouldn't be opposed to adding one though! Feel free to send a pull request. Only caveat: You'd need to add some docs as well (which can be brief, but not nonexistent).

**Comment by nevf** [comment]
@LeaVerou ```timeout``` is an XMLHttpRequest option that as per your doc's, you pass through. I'm afraid I'm snowed under right now re. a pull request.
