### ISSUE TITLE
Calling a `$.add` plugin from $$() 

### ISSUE THREAD

**Issue by thany** [LeaVerou/bliss#183]
I would be cool to be able to call a plugin on a `$$(...)` selector, that was added via `$.add` where the `this` variable in that plugin would correspond to the **array** of elements, rather than it getting called for each item one by one.

So consider:
```
$.add("myplugin", function() {
  console.log(this);
});

$$("div")._.myplugin();
```
I would like to have the logged `this` in this example to be the array that contains all divs. perhaps as an option to `$.add`.

The reason for this is a more efficient way to define more complex plugins, like so:
```
$.add("myplugin", function() {
  // some shared stuff here, like event handlers, data, whatever

  this.forEach(function(element) {
    // do something per element here
  });
});
```
This works fine when called element by element, however all "shared stuff" will be reinitialized on each call, which is less efficient than calling this plugin once.

On the other side, as some may not realize, it is possible to rewrite such a plugin to have once-initialized data, without any change to Bliss. But I don't think it will be an obvious solution and such code may look slightly too obnoxious for novice programmers:
```
$.add("myplugin", (function() {
  // some shared stuff here

  return function() {
    // do something per element here
  };
}()));
```
I'm not sure which is the best approach. One is more similar to jQuery, which might appeal more to novice programmers, while the other probably works fine, but requires more rewriting work when coming from jQuery and might not appeal to novice folks as much.

**Comment by LeaVerou** [comment]
Hi there,

In many cases, having `this` refer to the current element simplifies things. If you want `this` to refer to the whole array, just add your method to `$.Array.prototype` directly. :)

**Comment by thany** [comment]
True that.

Well, at least this may provide a solution for other people looking for this, either your approach or the one I suggested last :)

**Comment by LeaVerou** [comment]
Yup! Closing this now, for tidyness. :)
