### ISSUE TITLE
[Docs] Mistaken type for condition argument of $.include

### ISSUE THREAD

**Issue by gamtiq** [LeaVerou/bliss#186]
In documentation `String` is specified as type for `condition` argument of [$.include](http://blissfuljs.com/docs.html#fn-include). But the argument's value can be of any type because the value is coerced to a boolean. Perhaps `Boolean` should be assigned as `condition`'s type.

**Comment by LeaVerou** [comment]
Nice catch, thanks!
I removed the type completely as it could really be anything.
