### ISSUE TITLE
array merge

### ISSUE THREAD

**Issue by r3wt** [LeaVerou/bliss#19]
ever needed to merge 1 or more arrays?

adding this to the prototype is tacky, and would necessitate its own file. instead provide a function that takes infinite arguments. heres the prototype:
```js
var merge = function(){
	var args = [],
	result = [],
	unique = function(a,b) {
		var a = a.concat(b);
		for(var i=0; i<a.length; ++i) {
			for(var j=i+1; j<a.length; ++j) {
				if(a[i] === a[j])
					a.splice(j--, 1);
			}
		}
		return a;
	};
	Array.prototype.push.apply(args,arguments);
	for(k=0;k<args.length;k++){
		result = unique(result,args[k]);
	}
	return result; 
};
```
if you feel like its useful, just use it. no attribution necessary.

**Comment by zdfs** [comment]
@LeaVerou - Lea, is this something you want for Bliss? Just calling your attention to it.

**Comment by LeaVerou** [comment]
Hi there,
Thanks for the contribution! However, I’d rather avoid adding new lengthy methods to Bliss unless there's existing demand, at least for the time being.
