### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by minimok** [LeaVerou/bliss#196]
Your first example should surely be appending the 2 words "Hello" and "World" to a web page. That would be most useful.

**Comment by LeaVerou** [comment]
You don't need any library for that, just do:

```js
document.body.insertAdjacentText("beforeend", "Hello world");
```

**Comment by minimok** [comment]
Thx...that specific example wasn't actually the point :-) LOL

**Comment by LeaVerou** [comment]
Then perhaps you could try making an actual point? :)
