### ISSUE TITLE
1.0.3 release + npm 

### ISSUE THREAD

**Issue by tomdavies** [LeaVerou/bliss#197]
Hey, there are a decent number of fixes in the `gh-pages` branch relative to the latest version on npm  (the `v1.0.2` tag). 

Any chance of a pushing a new tag for these? 

Just spent better part of a day chasing down a bug that's was fixed in `gh-pages` back in April 2016, but I'd installed Bliss via `npm`, so only had `v1.0.2`.

**Comment by LeaVerou** [comment]
I made a new release, ran `npm publish`, no errors, but for some reason npm insists that the latest version is v1.0.2. https://www.npmjs.com/package/blissfuljs
No idea what to try next :(

**Comment by tomdavies** [comment]
Thanks for the quick reply - looks like [npm has caught up now](https://www.npmjs.com/package/blissfuljs)

**Comment by LeaVerou** [comment]
So I guess they implemented some sort of caching. Well, that was frustrating! Glad it was ok in the end.
