### ISSUE TITLE
Bliss.fetch doesn't expose the xhr, so cannot call abort()

### ISSUE THREAD

**Issue by kajmagnus** [LeaVerou/bliss#198]
Hi, I'd like to sometimes abort an ongoing HTTP request, by calling `xhr.abort()`. But `Bliss.fetch()` returns a Promise only, via which I cannot access `xhr.abort()` ( https://github.com/LeaVerou/bliss/blob/gh-pages/bliss.shy.js#L374 )

What do you think about somehow making `xhr.abort()` accessible? or the whole `xhr`.

And how can that best be done? My first thought was to add an `abort()` function on the returned promise, but that doesn't work so well, because it disappears when chaining with `.then(...)`.

(Currently I've done a quick hack in `bliss.shy.js`: I added `xhr` as a field on the promise, although it disappears when calling `then()`.)

**Comment by LeaVerou** [comment]
That's such an excellent point!

I'm not sure what the API should look like, but we should **definitely** address this somehow.

So far, the best way I can think of is the `xhr` property you added on the promise. But there must be a better way…

**Comment by kajmagnus** [comment]
I googled for `html5 fetch api` and found this: https://developer.mozilla.org/en-US/docs/Web/API/FetchController — however, it's experimental, and ... to me, looks a bit complicated.

So I agree with you that for the moment, probably just adding `xhr` on the promise, is a good approach.

Perhaps wait one .. two ... three years and see what'll happen with the fetch api spec :- )
perhaps later there will be a polyfill or sth like that, which exposes `abort()`.

Not sure if, meanwhile, it makes sense to add the `xhr` to the Promise in Bliss' master repo. This is how my hack looks like: https://github.com/debiki/ed-server/commit/4d46eecc70fb21a7735b7313591b161aacf051b6.

**Comment by LeaVerou** [comment]
If you want to send a PR with your changes, I'd merge it!

**Comment by kajmagnus** [comment]
Ok, I'll do :- )

**Comment by kajmagnus** [comment]
Closing this then, since the PR got merged. B.t.w. now I've ported the essential parts of my app from jQuery, to mainly React, + some Bliss also :- )
