### ISSUE TITLE
What should be the actual name?

### ISSUE THREAD

**Issue by lipis** [LeaVerou/bliss#20]
I think you have to stick to one..

https://github.com/LeaVerou/bliss/blob/gh-pages/package.json#L2
https://github.com/LeaVerou/bliss/blob/gh-pages/bower.json#L2
https://github.com/LeaVerou/bliss/blob/gh-pages/index.html#L6
https://github.com/LeaVerou/bliss/blob/gh-pages/index.html#L15

- Bliss
- Blissful
- Blissful.js
- Bliss.js

I know it's the hardest part.. but I think we'll have to use one :)

**Comment by LeaVerou** [comment]
The name is always bliss or blissfuljs if bliss is not available. :)
