### ISSUE TITLE
Fetch is incompatible with multipart

### ISSUE THREAD

**Issue by friday** [LeaVerou/bliss#202]
`Content-Type` must be undefined for multipart requests. Bliss's `fetch()` always sets `Content-type`, so multipart is impossible, See https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post and https://github.com/LeaVerou/bliss/blob/gh-pages/bliss.js#L366-L368

One solution would be to check the data and only set Content-type for strings:
```js
if (env.method !== "GET" && typeof env.data === "string" && !env.headers["Content-type"] && !env.headers["Content-Type"]) {
  env.xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
}
```

**Comment by LeaVerou** [comment]
Doesn't `headers: { "Content-Type": undefined }` work?

**Comment by friday** [comment]
It doesn't.

`!env.headers["x"]` doesn't distinguish between between passing a "falsy" `x` value or passing no `x` value.

If you want to enable, `headers: { "Content-Type": undefined }` you could replace the conditions with it with `!("x" in env.headers)` though.

I agree with you that this is a safer/less controversial approach in terms of compatibility. Do you want me to try it out and submit a PR?

**Comment by LeaVerou** [comment]
Yes please! Thank you so much! 😀

**Comment by friday** [comment]
Fixed in https://github.com/LeaVerou/bliss/commit/7ee2577b8b4eea2765209b2b2c7f6182c38d1842: You can now pass `headers: {"content-type": undefined}` ("content-type" being case-insensitive) to use the content-type set by the browser. I'll probably create another issue with a suggestion similar to #203 however (sorry @LeaVerou ;))
