### ISSUE TITLE
Handling upload events in $.fetch() via options

### ISSUE THREAD

**Issue by friday** [LeaVerou/bliss#204]
[xhr.upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload) has events too, just like the xhr-object. For example "onprogress".

$.fetch() allows you to assign to the xhr-object by passing "remaining" (not documented) options to it. However, with uploads you'd more likely want to pass them to xhr.upload, not xhr.

The best solution I could think of (backwards compatible and allows you to add properties to either) is to add properties to upload if passing them in `options.upload`.

Ex:

```js
$.fetch('/my/url', {method: 'POST', onprogress: downloadProgressHandler, upload: {onprogress: uploadProgressHandler}})
```

Doing that today leads to an error `TypeError: Cannot assign to read only property 'upload' of object '#<XMLHttpRequest>'`. So the change would definitely be non-breaking.

**Comment by LeaVerou** [comment]
Agreed, that would be a good syntax for it. PR? :)

**Comment by friday** [comment]
I will wait until #205 is closed to avoid conflicts.

**Comment by friday** [comment]
Added in #207
