### ISSUE TITLE
NPM package missing minified versions

### ISSUE THREAD

**Issue by nikolay-borzov** [LeaVerou/bliss#214]
It's useful to have a minified version for projects that don't minify prodcution code (e.g. user scripts)
I guess it's caused by https://github.com/LeaVerou/bliss/commit/43e76d1a9750c805f04724a44967459981723e7d

**Comment by LeaVerou** [comment]
The minified versions exist on the website, they are just not tracked in the repo anymore, to prevent conflicts.
http://blissfuljs.com/bliss.min.js
http://blissfuljs.com/bliss.shy.min.js

**Comment by nikolay-borzov** [comment]
Ok then. It's still not very convenient to reference http://blissfuljs.com/bliss.shy.min.js from code

**Comment by friday** [comment]
Excluding the builds from the git repo was certainly a great move, but it's very easy to override for npm: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
