### ISSUE TITLE
Files for CDN hosting (cdnjs)

### ISSUE THREAD

**Issue by extend1994** [LeaVerou/bliss#215]
Hi I am a member from [cdnjs](https://github.com/cdnjs/).
cdnjs have hosted v1.0.0 ~ v1.0.4 of bliss.
Recently, I noticed that of all front-end files in the latest release v1.0.5, only `bliss.shy.js` left compared to previous release. I know it's because https://github.com/LeaVerou/bliss/commit/43e76d1a9750c805f04724a44967459981723e7d
Unfortunately, in this case cdnjs could not grab other front-end files including `bliss.js`, `bliss.min.js` & `bliss.shy.min.js` because cdnjs uses a "auto-update" script to grab front-end files in library releases.
Could you tell me is it okay cdnjs only hosts `bliss.shy.js`? Or there are other possible solution for this?

Thank you!

For more details about auto-update, you can refer https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by LeaVerou** [comment]
Hi there,

We switched to using a build script on the server and removed generated files from the repo to prevent conflicts. I believe this is pretty common, and thought cdnjs has a way around it.
The files are still on our website, e.g. http://blissfuljs.com/bliss.min.js
Is there anything I could do to help cdnjs grab them?

**Comment by extend1994** [comment]
Thanks for quick reply!
Currently, cdnjs can only grab files of releases on npm or git repo (normally GitHub) "automatically". 
We can get files from your website and then "manually" add them to cdnjs, which is not good in the long term.
I think It would be great if it's possible for you to publish `bliss.min.js` & `bliss.shy.min.js` in v1.0.5 on npm!  (`bliss.js` & `bliss.shy.js` are already there)
Like previous versions, there are all front-end files (`bliss.js`, `bliss.min.js`, `bliss.shy.js`, `bliss.shy.min.js` I think).

**Comment by LeaVerou** [comment]
Oh, I didn't know you could add files to npm that are ignored in git!
I created an `.npmignore` but I can't publish it over the previously published npm version.
Do you know of any other way to do this besides releasing a new version?

**Comment by extend1994** [comment]
If I am not misunderstanding you, all front-end files I mentioned above would appear in the future versions on npm, right?
In this case, I can manually add v1.0.5. cdnjs auto-update script will grab future versions :)

**Comment by LeaVerou** [comment]
Yes, thank you!

**Comment by extend1994** [comment]
Thank you too! I will resolve cdnjs/cdnjs#12318 ASAP!
