### ISSUE TITLE
Calling `set` on arrays with an object fails

### ISSUE THREAD

**Issue by kimroen** [LeaVerou/bliss#22]
As an example, try this code in the console on the [Bliss Docs page](http://blissfuljs.com/docs.html):

```js
$$("h1")._.set({className: "title"});
```

This fails with the following error in Chrome:

```
Uncaught TypeError: Cannot read property 'map' of undefined
    at HTMLHeadingElement.$.Array.(anonymous function) (http://blissfuljs.com/bliss.js:575:25)
    at http://blissfuljs.com/bliss.js:576:44
    at Array.map (native)
    at Object.$.Array.(anonymous function) [as set] (http://blissfuljs.com/bliss.js:575:26)
```

The error points at this line: https://github.com/LeaVerou/bliss/blob/10bd9ad6e4231fa3399d6e4cfac7ef6d06e2d6d4/bliss.js#L575

There is a failing test for this included in the tests for `$.set`, over at #21.

**Comment by LeaVerou** [comment]
Thanks man! Wow, that was a pretty serious bug I introduced there last night!!
