### ISSUE TITLE
Memory leak bug in unbind method

### ISSUE THREAD

**Issue by hopeful2** [LeaVerou/bliss#221]
Hi Lea,

There is a bug in $.unbind method that may contribute to rapid memory leak and causes failures to remove anonymous handlers. It works together with a bug in Mavo to amplify the memory leak problems in Mavo apps. I am filing this issue here so other Bliss users can be aware of this when searching through issues.  I will submit a separate bug report to Mavo repo shortly.

## The bug

When a listener is registered using $.bind method for the first time, a record is ALWAYS pushed to an array in $.listeners, under the key of event type. 

When a listener is removed using $.unbind method, if both event type and callback are given, $.unbind will attempt to remove the listener from the element, without going through $.listeners registry. The record is never removed from the array. If the handler function contains reference to other objects in context, it will prevent these objects from garbage collection.

If the function is anonymous, the event listener is not removed from the element.

To verify the bug, please go to https://mavo.io/docs/primer, edit any field with a popup editor, show and hide the popup editor for a few times, and check the data array in console. 

$.listeners.get(document).click

You will see that the data array keeps increasing, even after $.unbind removes the listeners successfully.

## Solution

If data arrays exist for an element in $.listeners,  $.unbind should always go through the data arrays and remove both the records and event listeners. 

I will modify my current PR on $.unbind to address this issue. 

Best regards.

Oliver

**Comment by LeaVerou** [comment]
Oh I see, I understand the fix now, ignore my question in the PR!
