### ISSUE TITLE
[Docs] Table of contents not showing

### ISSUE THREAD

**Issue by Keyacom** [LeaVerou/bliss#256]
At https://blissfuljs.com/docs, the table of contents is supposed to show under "Contents", but it doesn't. No exception has occurred.

**Comment by LeaVerou** [comment]
> This project might be abandoned, which is a shame.

Not quite to that level, but certainly deprioritized. There is a near-complete rewrite to ESM in the v2 branch, but none of us had time to actually work on updating the website for v2. If any of you wants to help out, I'd be more than willing to provide guidance!
