### ISSUE TITLE
Let elemens be created using the <tag> syntax

### ISSUE THREAD

**Issue by kurtextrem** [LeaVerou/bliss#29]
jQuery:
`$('<div>')`

wouldn't sacrifice perf too much if only the first char is checked `expr[0] === '<'`, call `create(expr.slice(1, -1)`

**Comment by LeaVerou** [comment]
Actually, I think the same function doing completely different things is a bit of a usability problem. This is why there's also a separate `$.ready()` instead of overloading `$()` (which I considered for very long).
Not a super strong opinion though. :)
Thanks for posting a suggestion!
