### ISSUE TITLE
Errors in Safari

### ISSUE THREAD

**Issue by jdcauley** [LeaVerou/bliss#34]
Project Home page http://blissfuljs.com/ crashes safari
http://d.pr/i/1lK4X

Safari 9.0.1
OSX 10.11.1 (El Capitan)
MacBook Pro (13-inch, Mid 2012)

**Comment by LeaVerou** [comment]
I have almost exactly that setup and cannot reproduce…

**Comment by zdfs** [comment]
I see the error, but it's not crashing the page.

**Comment by LeaVerou** [comment]
Oh right, I see the errors too! Will look into it asap.

**Comment by zdfs** [comment]
Does the `EventTarget` object not exist in Safari?

**Comment by LeaVerou** [comment]
It doesn’t, but that wasn’t the issue. Safari was blowing up when iterating over `HTMLElement.prototype`, and even `try...catch` didn’t suppress the errors!!
Try for yourself in the console:

```js
try { HTMLElement.prototype.dir } catch(e){}
```

I solved it in 2db03517fd2d9a1a25e09db3995d6a2850df5ede by subsetting the object with only the properties that were actually functions on a dummy element.  (as a side note, I love, love, love the whitelist parameter on `$.extend()`! Surprising other libs don’t implement something similar. It’s so useful!)
