### ISSUE TITLE
Remove Chrome from Karma config?

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#35]
Thinking about taking Chrome out of the Karma config, just to remove those errors in the build. Seems pretty simple for anyone working on the project to add Chrome if they want it. Personally, I'm ok with just PhantomJS.

Thoughts?

**Comment by dperrymorrow** [comment]
thats cool, when writing test i like to have a physical browser so that i can debug in the console via debugger statements, but yes for CI Phantom only would be the way to go it seems.

**Comment by zdfs** [comment]
Agreed.

**Comment by zdfs** [comment]
This is merged. Closing out.
