### ISSUE TITLE
Tests for $()

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#38]
Putting this as a placeholder. I'm starting work on these.

**Comment by dperrymorrow** [comment]
is there a section of code you would like me to work on tests for? 
looks like ``clone`` is next up if going by order of the documentation of methods.

**Comment by LeaVerou** [comment]
I’d suggest leaving `clone` last, as it’s only present in Bliss Full.

**Comment by guoguo12** [comment]
Wait, is Bliss Full a pun?

@dperrymorrow: I'll do tests for `$.around`, so you can do `$.after` if you want.

**Comment by zdfs** [comment]
Would you all mind making an individual issue for the tests you're writing? That way, we know what's being worked on?

**Comment by guoguo12** [comment]
Sure.

**Comment by zdfs** [comment]
Changelist for this: 630947d6336d830574eea60350a27c7aba313238
