### ISSUE TITLE
Tests for Objects & Arrays

### ISSUE THREAD

**Issue by dperrymorrow** [LeaVerou/bliss#46]
Ill start with ```all``` and go from there. Ill pull request off my branch after i finish up tests for each of these methods.

Not that I'm reserving all of this, just opening an issue for where I would like to work.

> for those who have been irreparably damaged by Java-like languages.

so funny...

**Comment by LeaVerou** [comment]
Awesome, thanks so much!!

**Comment by zdfs** [comment]
@dperrymorrow  - Regarding your last PR, If you can add `sinon` to `package.json` as a straight dependency, we won't run in to NPM problems later. Just FYI.

**Comment by dperrymorrow** [comment]
oh you mean vs dev? Wouldnt that only be needed in dev *running the suite*?
if so, should I move the other frameworks karma is including as well?

```frameworks: ['mocha', 'sinon', 'fixture', 'chai'],```

**Comment by zdfs** [comment]
You can put `sinon` in the `devDependencies`. What I'm worried about is how NPM handles peer-dependencies. For example, `karma-sinon` downloads `sinon` for you, but I don't think that's the case with the latest versions of Node.

**Comment by dperrymorrow** [comment]
ah, gotcha. will do.
good to know, i think a glazed over a warning on the console about just that :)

**Comment by zdfs** [comment]
Gracias.

**Comment by dperrymorrow** [comment]
working on $.lazy will have a pull shortly

**Comment by dperrymorrow** [comment]
would you like me to take a stab at this ```// FIXME```
or just have tests that fail for it? 
or just ignore the fact that it cant override prototype properties?

```javascript
lazy: function(obj, property, getter) {
  if (arguments.length >= 3) {
    Object.defineProperty(obj, property, {
      get: function() {
        // FIXME this does not work for instances if property is defined on the prototype
        delete this[property];
        //...
```

**Comment by LeaVerou** [comment]
Of course, if you want to! Thanks!
But yeah, in a separate PR :)

**Comment by dperrymorrow** [comment]
I can't seem to write a failing test for ```$.lazy``` not being able to overwrite prototype properties with a getter. 

Do you have any suggestions for how I can replicate what you described in the ```// FIXME```

**Comment by dperrymorrow** [comment]
last night and just now, I have added 
- tests for ```$.type``` https://github.com/LeaVerou/bliss/commit/2e0b85d424742af742edfbfac5d78f13e62cd866
- tests for ```$.extend`` https://github.com/LeaVerou/bliss/commit/d81d04900a8aeb2540d140bacfd7749a3f3b077c

**Comment by LeaVerou** [comment]
If you can't reproduce, it might not be a valid issue. Don't stress over it, just remove the comment :)

**Comment by dperrymorrow** [comment]
Ok, have prototype properties in the tests, and they seem to work fine. 
moving on...

**Comment by zdfs** [comment]
Close this out?

**Comment by dperrymorrow** [comment]
yeah closed, ill make separate issues for each object / arrays method i write tests for, 
only a couple left to go...
