### ISSUE TITLE
z-index issue on bliss site

### ISSUE THREAD

**Issue by dperrymorrow** [LeaVerou/bliss#54]
in Chrome 47.0.2526.73 (64-bit)
there is a z-index issue with the stripes under the code snippets.

Locally i do not see this issue. It must have been resolved but not deployed.

![bliss js documentation 2015-12-08 14-52-54](https://cloud.githubusercontent.com/assets/64978/11671231/a41d7042-9dbb-11e5-8ce7-7de1c7ac2c0d.png)

**Comment by guoguo12** [comment]
Confirmed; this was caused by 35664aeeebe847c46c00f7b3f2940e13339add42.

**Comment by zdfs** [comment]
This is fixed.
