### ISSUE TITLE
Should we move to a src and dist directory structure?

### ISSUE THREAD

**Issue by praveenpuglia** [LeaVerou/bliss#59]
It's not high priority but right now even changing the gulp file triggers the watch. It would probably be better to move the src in *src* directory and generated files in *dist* directory?

**Comment by kurtextrem** [comment]
:+1:

**Comment by kurtextrem** [comment]
Maybe also auto generating the shy version is a good idea as well.

**Comment by shshaw** [comment]
As someone trying to parse the bliss code for the first time, `src` and `dist` dirs would be quite helpful!

**Comment by zdfs** [comment]
@LeaVerou What do you think about this. I was also wondering if we should separate the actual code development to a `master` branch, leaving the `gh-pages` branch for the docs. Might make it easier to tag releases.

**Comment by guoguo12** [comment]
I'm a fan of both `src`/`dist` and `master`/`gh-pages`. Or, at the very least, we should move `index.js` and `transform.js` into a subdirectory, just to make it clear those aren't part of the actual library.

**Comment by praveenpuglia** [comment]
:+1: both @zdfs & @guoguo12

**Comment by LeaVerou** [comment]
I have this issue with most of my projects, so I would definitely welcome a solution :(
The problem is, I want to have access to the current builds on gh-pages (e.g. for downloads or for the actual site), but without having to duplicate them. Any ideas? AFAIK git submodules don't work for branches, just directories…

:+1: to @guoguo12, yes, if we keep everything in the same dir, moving the website js files to a folder is probably a good idea. 

@kurtextrem Not sure what you mean. bliss.shy.js is the source, bliss.js is auto-generated.

**Comment by zdfs** [comment]
Could just have the source in `master` and then when we release, pull it in to `gh-pages` via npm and do a gulp task for copying the files somewhere for downloading?

**Comment by praveenpuglia** [comment]
@LeaVerou can we not have the download links point to the **raw.github...** of the generated files on master?

**Comment by LeaVerou** [comment]
@zdfs Then it's yet another manual step, that I'd rather avoid. Also, I'd rather have the current version on the website, not the last "release". 
@praveenpuglia I think that’s generally discouraged, no? Also, one more DNS lookup.

**Comment by zdfs** [comment]
Ok. So let's define what we have so far.

1. There's been a request for tagged releases on Github.
2. There's been a request for `src` and `dist` folders in the project.
3. Lea would like the latest version for download at any time.

Missing anything?

**Comment by praveenpuglia** [comment]
@LeaVerou curious why that's discouraged. Anything other than DNS lookup issue?

**Comment by guoguo12** [comment]
@zdfs: I think that sums it up. I also suggested moving the website JS files into a separate subdirectory, but that can be addressed later.

**Comment by LeaVerou** [comment]
Should I wait until we decide on this before I start tagging releases?

**Comment by zdfs** [comment]
@LeaVerou - We can start tagging, that won't get in the way of anything. I'm just attempting to try and find a holistic solution we can all execute on.

**Comment by zdfs** [comment]
I think we have most of our criteria.

Ideas. Suggestions. The floor is open.

**Comment by LeaVerou** [comment]
Isn't 4 tied to 1? If releases are being tagged, I can just npm publish, no?

**Comment by dperrymorrow** [comment]
you could link to the latest version on master from the ```gh-pages``` branch.
You simply link to the raw file on github on the master branch. 
__for example:__ https://raw.githubusercontent.com/LeaVerou/bliss/gh-pages/bliss.shy.min.js

that way gh-pages could simply be the docs website as one would expect.

**Comment by shshaw** [comment]
You may need to use a service like [RawGit](https://rawgit.com/) in order to have the script run on the page. GitHub does not return the right headers when embedding a script from the raw URL, but RawGit gets around that.

**Comment by dperrymorrow** [comment]
oh, so does bliss website need the latest to execute, or just offer for a download link? 
couldn't the website just be built off of whats recent on NPM?

**Comment by LeaVerou** [comment]
Relying on a third party service like rawgit makes me a bit uneasy.
Is there a way (maybe a post commit hook?) to copy files from master to gh-pages without any extra manual steps?

**Comment by zdfs** [comment]
@LeaVerou - Domenic has something like this: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by guoguo12** [comment]
Any consensus on this? @zdfs: I like the Domenic script provided that it can be set up easily.

**Comment by dperrymorrow** [comment]
@guoguo12 there is also talk of an html page on the site with tests running so that could complicate this issue #71

**Comment by zdfs** [comment]
There are things we can try, but no work has started. I guess we could make a `master` from `gh-pages` and see how far we get with the build to see if we can satisfy all the use cases, moving everyone to master if we're successful. Any volunteers?

**Comment by praveenpuglia** [comment]
I am here!

**Comment by zdfs** [comment]
Ok. Just so we can make some progress on this story. I'm going to branch `gh-pages` to `master`. @praveenpuglia, am I correct in assuming you'd like to give it a shot. You up to date on this thread? Know all the use cases we want to solve?

**Comment by wcastand** [comment]
i'm available too for testing or helping :)

**Comment by zdfs** [comment]
Ok. Branch is made.

**Comment by praveenpuglia** [comment]
@zdfs - Yep. But if I do something stupid, you would know! :)

**Comment by wcastand** [comment]
do we need to make a slack or something.
That could help organize et don't make the same thing twice no ?

**Comment by zdfs** [comment]
I can do that.

**Comment by zdfs** [comment]
I made a Slack instance at https://blissjs.slack.com/.

**Comment by praveenpuglia** [comment]
Says I am not in that team. This email - praveenpuglia@gmail.com ?

**Comment by wcastand** [comment]
same here. email : wcastand@gmail.com

**Comment by zdfs** [comment]
I'll take a look and send out invites.

**Comment by zdfs** [comment]
Closing this for #82.
