### ISSUE TITLE
More tests for $.delegate

### ISSUE THREAD

**Issue by guoguo12** [LeaVerou/bliss#60]
I'm working on this! I want to cover all of the ways `$.delegate` can be used.

**Comment by zdfs** [comment]
Awesome @guoguo12. Thank you.

**Comment by LeaVerou** [comment]
Thank you so much @guoguo12!!

**Comment by wcastand** [comment]
Ok i will do the other events then, i guess.

**Comment by LeaVerou** [comment]
@guoguo12 You’ve got mail :)

**Comment by guoguo12** [comment]
Add some tests with 7cfe299150594398161d38b10ba6c292a3034cf3. They could be more comprehensive, but I'm closing this for now.

**Comment by zdfs** [comment]
@guoguo12 - The build is failing because the `$.delegate` tests seem to be failing. Can you take a look?

**Comment by guoguo12** [comment]
Yep, I'll look into it. Sorry @wcastand for the trouble at #78!

**Comment by guoguo12** [comment]
Well, everything still works fine for me locally, just like it did when I pushed. Could it be because of 20a444457989e9043422ad35f0f4573715f796a0?

**Comment by wcastand** [comment]
No problem the test for you delegate actually worked on my computer too.
So that's weird.

**Comment by zdfs** [comment]
I'm re-running the build to see if it fails again.

**Comment by zdfs** [comment]
And it does.

**Comment by guoguo12** [comment]
All seven of my `$.delegate` tests fail now, but the test I had at edb5836a4d793fcf7b973eb1581b6c71ef1f7a67 passed.

**Comment by wcastand** [comment]
i pulled the repo and did ```karma start``` again:
```
$ karma start
11 12 2015 18:19:23.723:WARN [karma]: No captured browser, open http://localhost:9876/
11 12 2015 18:19:23.733:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
11 12 2015 18:19:23.738:INFO [launcher]: Starting browser Chrome
11 12 2015 18:19:28.647:INFO [Chrome 47.0.2526 (Windows 10 0.0.0)]: Connected on socket e8cFM6NajWVqnohQAAAA with id 77160642
Chrome 47.0.2526 (Windows 10 0.0.0): Executed 89 of 89 SUCCESS (0.191 secs / 0.05 secs)
```

It's still working for me.

**Comment by guoguo12** [comment]
Maybe it's because I took out the

```js
document.body.appendChild(subject);
```

I'll make a commit to check.

**Comment by guoguo12** [comment]
It worked! https://travis-ci.org/LeaVerou/bliss/builds/96316088

**Comment by wcastand** [comment]
So we need to relaunch test on Pr or i need to make and other PR ?

**Comment by zdfs** [comment]
I'll re-run the builds now.
