### ISSUE TITLE
Compatibility with jQuery Plugins

### ISSUE THREAD

**Issue by Kikobeats** [LeaVerou/bliss#63]
Just I want to know if is in the target of the library be compatible with jQuery Plugins.

These Plugins need jQuery.fn namespaces. Actually I never implemented one, so I'm not sure if need something specific of the jQuery core or really depend of each plugin implementation.

Could be very interesting unlock this power using bliss!

**Comment by LeaVerou** [comment]
No, the library is not "jQuery’s API, just lighter". It has its own API. In fact, one of the reasons I don’t use jQuery is that I dislike parts of its API. I think [Zepto](http://zeptojs.com/) might be closer to what you’re looking.
Hope this helps!

**Comment by Kikobeats** [comment]
all right! 🙌
