### ISSUE TITLE
Test for $.events

### ISSUE THREAD

**Issue by wcastand** [LeaVerou/bliss#66]
Hi again,
I must be really dumb lol.
So, i test [$.events](http://blissfuljs.com/docs.html#fn-events)
Right now,i only tested with the global syntax ( $.event(subject, handlers) )
```javascript
describe("$.events", function() {
	it('exists', function() {
		expect($.events).to.exist;
	});
	describe("use with global", function() {
		it("Set multiple event listeners on an element based on element", function(done) {
			var subject = document.createElement("input");
			subject.type = "text";
			subject.id = "test";
			document.body.appendChild(subject);

			var clone = document.createElement("textarea");
			clone.addEventListener("input", function(e){ done(); });
			clone.addEventListener("click", function(e){ done(); });
			$.events(subject, clone);

/*			var ev = document.createEvent("MouseEvent");
			ev.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
			subject.dispatchEvent(ev);*/
			subject.value = "test";
		});
[...]
```
So the test is a success with the click event, but failed when i just change the value of the input.
If it was copying the events from the element, the test should pass with click event and input event.

The input event is implemented on both input and textarea. [doc](https://developer.mozilla.org/en-US/docs/Web/Events/input)

I also tried with my own handler (not cloning from an other elements) and it didn't work at all.
```javascript
		it("Set multiple event listeners on an element", function(done) {
			var subject = document.createElement("input");
			subject.type = "text";
			subject.id = "test";
			document.body.appendChild(subject);

			$.events(subject, {
				'oninput onclick': function(e){ done(); }
			});

			var ev = document.createEvent("MouseEvent");
			ev.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
			subject.dispatchEvent(ev);
		});
```

I don't know if i do things badly or i am just unlucky but i'm not really helping right now, i can't make a single test work :/
Sorry guys.

**Comment by zdfs** [comment]
You're not dumb. Let's make that pristine. None of us are going to make you feel that way. Bliss is a learning tool as well as a nice utility. 

Now that I have that out of the way, we can all take a look and see if we can help.

**Comment by guoguo12** [comment]
Yeah, @wcastand, you're doing great work. For example, your test for `$.delegate` was well designed and it passed on both Chrome and Firefox; it was totally PhantomJS's fault that it was failing. Don't be too hard on yourself. :smiley:

**Comment by zdfs** [comment]
Agreed with @guoguo12. That test is part of the suite now. It was Phantom that was screwing up.

**Comment by zdfs** [comment]
@wcastand - Comment out your test file and commit the code. We can all download your tests and play around, see if we can't spot the issue.

**Comment by zdfs** [comment]
This test is in the repo. If we can take a look and see if we can help, that would be great.

**Comment by LeaVerou** [comment]
In the second example, it should be `"input click"`, i.e. without the "on".
The first one is really odd, no ideas right now…

**Comment by wcastand** [comment]
Ok so the second worked with "input click".
We should update the doc on blissfuljs.com then because the example look like this:
```javascript
$$('input[type="range"]')._.events({
	"oninput onchange": function(evt) { this.title = this.value}
})
```

I don't know if the use of ```$$()._.events()```  change somethins about the ```"oninput onclick"``` or ```"input click"```

**Comment by zdfs** [comment]
I don't think setting the input value via javascript is the same as the user setting the input value. I don't think the change event is getting called (or the input event). I think it requires an actual user?

**Comment by LeaVerou** [comment]
Oh, you were changing the value via JS? Yeah, that doesn't fire an input event. I thought you were changing it manually!

**Comment by wcastand** [comment]
The mozilla doc write that: 
Also the change event is related. change fires less often than input – it only fires when the changes are committed by the user.

**Comment by zdfs** [comment]
So I have this:

```
it("Set multiple event listeners on an element based on element", function(done) {

	//Create elements
	var subject = document.createElement("input");
	var clone = document.createElement("textarea");
	var htmlEvt = document.createEvent("HTMLEvents");
	var calls = {
		input: 0,
		click: 0
	};

	// Add properties to the input and add it to the body.
	subject.type = "text";
	subject.id = "test";
	document.body.appendChild(subject);

	htmlEvt.initEvent('input', true, true);

	clone.addEventListener("input", function(e) {
		calls.input += 1;
		done();
	});

	clone.addEventListener("click", function(e) {
		calls.click += 1;
		done();
	});

	$.events(subject, clone);

	subject.value = 'test';
	subject.dispatchEvent(htmlEvt);

	expect(calls.input).to.equal(1);
	expect(calls.click).to.equal(0);

	clone.click();

	expect(calls.input).to.equal(1);
	expect(calls.click).to.equal(1);

});
```

It passes, but is it what we want?

**Comment by dperrymorrow** [comment]
my 2 cents, i would use spies to keep track of the call count, makes the code cleaner too you dont have to write any functions

```javascript
var spy = sinon.spy();
clone.addEventListener("click", spy);
//...
expect(spy.wasCalledOnce).to.be.true;
```

im using spies in ```$.lazy ``` in a similar situation if you want an example.

**Comment by zdfs** [comment]
@dperrymorrow - Shit. Forgot about that. Thanks for the reminder.

Spies aside, is this how we would test something like this? Since we can't actually simulate being a user in a browser?

**Comment by zdfs** [comment]
```javascript
it("Set multiple event listeners on an element based on element", function(done) {

	//Create elements
	var subject = document.createElement("input");
	var clone = document.createElement("textarea");
	var htmlEvt = document.createEvent("HTMLEvents");
	var spy = sinon.spy();

	// Add properties to the input and add it to the body.
	subject.type = "text";
	subject.id = "test";
	document.body.appendChild(subject);

	htmlEvt.initEvent('input', true, true);

	clone.addEventListener("input", spy);
	clone.addEventListener("click", spy);

	$.events(subject, clone);

	subject.value = 'test';
	subject.dispatchEvent(htmlEvt);

	expect(spy.callCount).to.be.equal(1);

	clone.click();

	expect(spy.callCount).to.equal(2);

	clone.value = 'testclone';
	clone.dispatchEvent(htmlEvt);

	expect(spy.callCount).to.equal(3);

	done();

});
```

Updated with spies. What do we think?

**Comment by LeaVerou** [comment]
Thanks @zdfs! Yeah, can't think of any other way. Writing automated tests that involve user interaction is not exactly a solved problem, so simulating the event is our best bet.

**Comment by guoguo12** [comment]
When you do something like

```javascript
clone.click();
expect(spy.callCount).to.equal(2);
```

is it possible that the click doesn't get processed before the `expect` call?

**Comment by zdfs** [comment]
I haven't seen that happen yet, @guoguo12. Should I worry?

**Comment by zdfs** [comment]
I've added my version of the $.events tests. Take a look? See if we're all happy?

**Comment by LeaVerou** [comment]
@guoguo12 I believe `click()` is synchronous, so that shouldn’t happen…

**Comment by zdfs** [comment]
@wcastand - Were there more tests you wanted to write, or was that all of them? Did you have any questions on what we did?

**Comment by zdfs** [comment]
Closing this for now, since tests have been submitted.

**Comment by guoguo12** [comment]
@LeaVerou: Okay, I wasn't sure. For some reason I thought all JS events were queued in the event loop...

Anyway, this will make writing `$.delegate` tests easier.

**Comment by wcastand** [comment]
Okay, sorry guys i had to go to bed, it was 00h00 in France and i had to wake up at 5 :p 
So i have one suggestion and one question.
I think we should write one on the listener with the other synthax like:
```javascript
clone.oninput = spy  
```
So we can test the second loop of $.events. Because bliss process .onevent in a different loop.

And my question is, when we test and for example in ```$.events``` , we have multiple uses.
With an element, with a handler
but also with ```$.events()```, ```$('element')._.events()``` , ....

In the test do we need to test every use case or just one and assume that all the other possibility works fine too and only look at them if we have an issue at some point ?

Examples, in the case of $.events, do we need to write 2 tests like we did or 6 tests for each possibility ?
