### ISSUE TITLE
Test for $.clone

### ISSUE THREAD

**Issue by AVGP** [LeaVerou/bliss#67]
becase you do *not* only live once!

**Comment by zdfs** [comment]
Nice. Well played.

**Comment by jeremenichelli** [comment]
I can grab this one guys if it's not taken. Let me know.

**Comment by zdfs** [comment]
I think there's a PR for #70. Still ironing some things out. You could write tests for $.style() or $.start() @jeremenichelli?

**Comment by jeremenichelli** [comment]
SURE! I'll pick one and create an issue. Please sign this issue to you so
that everyone knows you're taking care of it 😊

On Thursday, 10 December 2015, Zachary Forrest y Salazar <
notifications@github.com> wrote:

> I think there's a PR for #70 <https://github.com/LeaVerou/bliss/pull/70>.
> Still ironing some things out. You could write tests for $.style() or
> $.start() @jeremenichelli <https://github.com/jeremenichelli>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeaVerou/bliss/issues/67#issuecomment-163483283>.
>


-- 
Jeremias Menichelli, Web Developer

*mail *jmenichelli@gmail.com
*twitter* @jeremenichelli
*g+* Jeremias Menichelli
*site* http://jeremenichelli.github.io

**Comment by AVGP** [comment]
@jeremenichelli I can't assign myself - if I could, I would've done it.

**Comment by jeremenichelli** [comment]
Oh didn't know that. Then a comment it's just fine.

On Thursday, 10 December 2015, Martin N. <notifications@github.com> wrote:

> @jeremenichelli <https://github.com/jeremenichelli> I can't assign myself
> - if I could, I would've done it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeaVerou/bliss/issues/67#issuecomment-163570029>.
>


-- 
Jeremias Menichelli, Web Developer

*mail *jmenichelli@gmail.com
*twitter* @jeremenichelli
*g+* Jeremias Menichelli
*site* http://jeremenichelli.github.io

**Comment by zdfs** [comment]
We can't assign people unless they're collaborators. So we've been using comments. Just an FYI.

On a separate note, is this done?

**Comment by AVGP** [comment]
@zdfs Yes, since #70 landed, this can be considered done
