### ISSUE TITLE
Karma Reporter

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#71]
@LeaVerou has mentioned it would be nice to have an HTML reporter where users can re-run the tests in the browser. I was looking at something like this: https://www.npmjs.com/package/karma-jasmine-html-reporter.

@dperrymorrow - Seen this anywhere with karma? Ideas.

**Comment by zdfs** [comment]
I don't see anything out there that works like QUnit, where you can re-run the tests in the browser.

Which begs the question, how important is this?

**Comment by dperrymorrow** [comment]
well if you reload the Chrome browser it launches, it does re-run the tests. 
Are we looking to have the tests suite as a page on the gh-pages site? Is that what you mean?

**Comment by zdfs** [comment]
@dperrymorrow - Yeah. That's the use case.

**Comment by dperrymorrow** [comment]
Using ```karma-htmlfile-reporter``` I'm able to generate a html file of the result of a Karma run.
Its not actually running the suite, but lists out all the tests ect...
![bliss unit tests - bliss unit tests 2015-12-09 16-52-47](https://cloud.githubusercontent.com/assets/64978/11703590/4b1d770a-9e95-11e5-9cce-42dc89d40f5a.png)

You could wire up an html page for the tests, but that would probally require checking the npm_modules dir into the project.

**Comment by zdfs** [comment]
Committing the node modules seems problematic.

**Comment by dperrymorrow** [comment]
i would agree, 
only thing i can think of at the moment would be to have a gulp task that makes a concatenated minified js file for the html test page from the src in of node_modules.

could work...

**Comment by zdfs** [comment]
If you wanted to spend some time seeing if something like could work, it might be worth releasing. Other than that, the only path forward I'm aware of is rewriting the tests in QUnit.

**Comment by dperrymorrow** [comment]
if we go down this road its just going to further complicate #59 though isn't it?

**Comment by zdfs** [comment]
Possibly. Just trying to figure out what our options are. @LeaVerou: how important is this to you?

**Comment by zdfs** [comment]
Closing this out for #82.

**Comment by dperrymorrow** [comment]
ok i can always take a stab later at building a gulp task to create a test web page.

**Comment by dperrymorrow** [comment]
IMO i think having CI in multiple browsers might be of more priority, with something like SauceLabs

**Comment by zdfs** [comment]
I think Browserstack or SauceLabs is a good idea. We can get a free account since this is open source.
