### ISSUE TITLE
Test case for $.once

### ISSUE THREAD

**Issue by fcalderan** [LeaVerou/bliss#75]
Looking into the source code I've found an undocumented method ```once``` and I've tested it: in this example I want to move one div twice, but I want to execute the ```transitionend``` handler just once.

**Expecting result**: the number inside the ```foobar```div should be increased one time in all browsers
**Actual result**: the number inside the div increases twice on Chrome ```47.0.2526.80 (64-bit)``` and ```Safari 9.0.2 (9537.86.3.9.1)``` and increases properly once on Firefox `42.0` on a  ```MacOSX 10.9.5``` (see screenshot below about the comparison between Chrome and Firefox)
**Hint**: it seems the problem is related to ```'webkitTransitionEnd transitionend'``` event type string: if I specify only ```'transitionend'``` the demo works as expected in all the tested browsers.

---

![once](https://cloud.githubusercontent.com/assets/380561/11712683/f31feafc-9f2e-11e5-9234-6782f987fa06.png)

---

This is my test case

```
<html>

    <head>
        <style>
        div {
            border: 3px #79b solid;
            display: inline-block;
            padding: 1em 3em;
            transform: translateX(0);
            transition: all 3s;
        }
        </style>
    </head>

    <body>

        <div id="foobar">0</div>
        <script src="bliss.min.js"></script>

        <script>
        $.ready().then(function() {
            var foobar = $('#foobar');
            foobar._.style({
                transform: 'translateX(160px)'
            });

            /* this is executed twice */
            foobar._.once('webkitTransitionEnd transitionend', function l(evt) {
                this.textContent = +this.textContent + 1;
                this._.style({
                    transform: 'translateX(0)'
                })
            });

            /* tried also this */
            /* foobar._.once({
                'webkitTransitionEnd transitionend': function l(evt) {
                    this.textContent = +this.textContent + 1;
                    this._.style({
                        transform: 'translateX(0)'
                    })
                }
            }); */


        });
        </script>

**Comment by zdfs** [comment]
It seems like Chrome understands both `webkitTransitionEnd` and `transitionend` events and executes once for each event?

**Comment by fcalderan** [comment]
@zdfs In this case I suppose that on chrome and safari the counter would be immediately ```2``` after the first animation (since they would be both executed once)

**Comment by LeaVerou** [comment]
Oh, `$.once()` is undocumented indeed! That was not on purpose, it was just forgotten. We/I need to document it :)
Nice test too. Easy to fix as well, I think (it just needs a loop where it removes the event). If nobody else fixes it by tomorrow, I'll push a fix (I have a deadline tomorrow, so can't do much right now).
Thanks for both catches @fcalderan!

**Comment by LeaVerou** [comment]
Does it pass now?

**Comment by fcalderan** [comment]
The test case works fine both in Chrome and Safari.

**Comment by LeaVerou** [comment]
Awesome, closing this then! Thanks @fcalderan!
