### ISSUE TITLE
Bower package not found

### ISSUE THREAD

**Issue by fgirardey** [LeaVerou/bliss#79]
Hi,

I tried to install bliss with bower (`bower install --save bliss`) and i've got the following response:

```
bower                        ENOTFOUND Package bliss not found
```

So i tried to install right from the github URL `bower install --save `https://github.com/LeaVerou/bliss.git` and i've got the following response:

```
bower bliss#*               not-cached https://github.com/LeaVerou/bliss.git#*
bower bliss#*                  resolve https://github.com/LeaVerou/bliss.git#*
bower bliss#*             ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in https://github.com/LeaVerou/bliss.git
```

I think that the package need his first tag 😇

**Comment by zdfs** [comment]
Closing this for #82.

**Comment by LeaVerou** [comment]
We have tags now :)
As to Bower, you need to specify that you want the gh-pages branch by using `#gh-pages` after the URL.
