### ISSUE TITLE
Help choose what chat solution we use!

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#81]
If you need access to the Slack instance at http://blissjs.slack.com, leave your email in a comment. I'll delete it when I've added you. 

Not sure how else to do this.

**Comment by guoguo12** [comment]
Thanks for setting this up! I'm guoguo12@gmail.com.

**Comment by dperrymorrow** [comment]
you could git log, all the authors email addresses should be listed.
dperrymorrow@gmail.com

**Comment by zdfs** [comment]
Nevermind. Join this instead! https://discord.gg/0hHWcV9ok6XDHGPe

**Comment by LeaVerou** [comment]
Actually, we’re running a poll on what chat solution we should use. Please vote! https://twitter.com/blissfuljs/status/675424420341538820

**Comment by zdfs** [comment]
So the twitter poll ended with IRC being the favorite. Are we going to move to IRC?

**Comment by praveenpuglia** [comment]
I would love to use Discord but I think signing up for another service is additional pain for people and hence they chose IRC may be!

**Comment by wcastand** [comment]
A trello could also be useful, i start to get lost in all this issues :/

**Comment by LeaVerou** [comment]
I've seen many open source projects use Slack recently. E.g. look at https://github.com/nylas/N1
People can just click on the slack button and join, no invitation necessary. Perhaps we shouldn't be quick to give up on slack?

**Comment by zdfs** [comment]
I'm happy to help set something up for Slack. I just figured that was something we ruled out. There were some nice sign up options that we could try.

**Comment by zdfs** [comment]
I.E. This: https://github.com/rauchg/slackin

We'll need to have a subdomain that we can point to, I think? A free-tier heroku server should suffice.

**Comment by dperrymorrow** [comment]
or also there is https://gitter.im/ its sort of a totally open slack.

**Comment by zdfs** [comment]
Yeah. I'm open to Gitter too. I think Slack has the brand recognition and a lot of people already use it at work. I'm open to whatever, but I'd like to decide on something and move forward, if we can.

**Comment by LeaVerou** [comment]
Gitter looks really cool! I’ve created a test room, let's try it out for a bit? https://gitter.im/LeaVerou/bliss

**Comment by zdfs** [comment]
I think Gitter is working out nicely.

**Comment by LeaVerou** [comment]
Agreed. Closing this for now, if gitter doesn't work out for whatever reason, we can always reopen. But I’m pretty psyched about gitter right now! Thanks for suggesting it @dperrymorrow!
