### ISSUE TITLE
Tests for $.properties

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#88]
I'm starting on this.

**Comment by zdfs** [comment]
Working on this, but for some reason, running in to a weird case where I set a boolean property like `disabled` but not `checked`. If anyone has any clues, I'd appreciate it.

**Comment by LeaVerou** [comment]
Can you share the exact failing code and more details about what happens?

**Comment by zdfs** [comment]
The failing test so far:

```javascript
it('sets some properties on an element', function() {

    var input = document.createElement('input');

    $.properties(input, {
        type: 'radio',
        disabled: 'disabled',
        checked: 'checked',
        className: 'hotline-bling',
        value: 'drake',
        onClick: function() { console.log('here'); }
    });

    console.log(input);

    expect(input.getAttribute('disabled')).to.exist;
    expect(input.getAttribute('checked')).to.exist;
    expect(input.getAttribute('type')).to.equal('radio');

});
```
And the output:

![screen shot 2015-12-14 at 10 47 59 am](https://cloud.githubusercontent.com/assets/619628/11790360/34ed352e-a250-11e5-9c12-a7bf04c26bbc.png)

**Comment by LeaVerou** [comment]
Ok, I see the problem now. It's not a bug, this is just how the DOM works.
First off, you’re setting the boolean properties `checked` and `disabled` to a string. That's ok though, as they will be converted to `true` since the string is truthy. But it's pointless and misleading.
Secondly, the `checked` and `disabled` **properties** are different than the corresponding **attributes**. Try it yourself in the console:
```js
input = document.createElement("input");
input.checked = true;
input.hasAttribute('checked'); // false
```

**Comment by zdfs** [comment]
Interesting. I'll change the property values. Thanks for looking.

**Comment by LeaVerou** [comment]
Note that the opposite is true: attributes do affect the properties:

```js
input = document.createElement("input");
input.setAttribute("checked", "");
input.checked; // true
```

**Comment by zdfs** [comment]
It's the `defaultChecked` property that I was looking for. Nice explanation on jQuery's documentation for `$.fn.prop()`.

**Comment by zdfs** [comment]
Closing this out. We're up to 123 unit tests.
