### ISSUE TITLE
Viewing method implementation for `$` and `$$` doesn't work as expected

### ISSUE THREAD

**Issue by kimroen** [LeaVerou/bliss#9]
I love this feature of being able to view the implementation right in the documentation!

There is a bug where the documentation for [`$()`](http://blissfuljs.com/docs.html#fn-$) is actually showing the implementation for [`$$()`](http://blissfuljs.com/docs.html#fn-$$), and the documentation for `$$()` shows `undefined`.

This is because [the code that finds the source](https://github.com/LeaVerou/bliss/blob/0ba792b6ab5d916b964bcb83e9d2f6fe20e298a6/index.js#L33) looks for the method name on the `$` object and the `$.sources` object.

This works fine for all of the other methods, but for these in particular, it doesn't work:

```js
$["$"];  // => The $.$() method, also known as $$()
$["$$"]; // => Undefined
```

**Comment by LeaVerou** [comment]
Gah, yeah, I should special case those. Thanks for the tip!!
