### ISSUE TITLE
Use fetch, instead xhr request

### ISSUE THREAD

**Issue by lukeapage** [LeaVerou/bliss#91]
Nice library!

It would be in keeping with the theme of the library to use fetch instead of xhr request - https://github.com/LeaVerou/bliss/blob/gh-pages/bliss.js#L263

You may want to just tell people to use fetch and not expose your own fetch object or wrap it  and optionally return something more similiar to fetch (e.g. one annoyance I find is needing a 2nd promise on the result instead of just getting the contents and automatically JSON.parse if the content type is json).

Spec: https://fetch.spec.whatwg.org/
Polyfill: https://github.com/github/fetch

**Comment by kurtextrem** [comment]
Hi, Lea already answered this one: https://github.com/LeaVerou/bliss/issues/31 (first response).

**Comment by lukeapage** [comment]
ok

**Comment by LeaVerou** [comment]
FWIW, you don't need to JSON.parse() if you use `responseType: 'json'`. And that's just native XHR functionality :)

**Comment by lukeapage** [comment]
w.r.t. json parse I meant the fetch standard e.g. https://github.com/github/fetch#json
Ok you don't have to call json.Parse, you can use the json helper method, but it is not done automatically if the response type is 'json'
