### ISSUE TITLE
Tests for $.start

### ISSUE THREAD

**Issue by HuzefaEzzi** [LeaVerou/bliss#94]
I am working on it.

**Comment by dperrymorrow** [comment]
good stuff, thanks for helping out!
few tips on tests in Bliss

- don't use other Bliss methods in your tests _(isolate the method you are testing as much as possible)_
- use HTML fixtures whenever possible vs creating DOM elements  with JS
- use spies or stubs for callback functions whenever possible

thanks

**Comment by dperrymorrow** [comment]
I just updated the README.md in the tests dir to reflect these suggestions.

**Comment by LeaVerou** [comment]
Thank you both!!

**Comment by dperrymorrow** [comment]
closing this after merging pull request #101
